# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'clf-deployment'
    regionName: 'us-east-1'
    stackName: 
    templateSource: 'url'
    templateUrl: 'https://github.com/Munisekhar371/aws-clf-test/blob/b6e348f329db84e67dcb53b1e467e6e0f122ddb9/secret-creation-template.yml'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
