AWSTemplateFormatVersion: "2010-09-09"
Description: "Template to create new secret manager"
Resources:
  Secret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: "AmazonMSK_DEVClusterSecrete"
      Description: "Secret  data for IC4E Tpi listener"
      KmsKeyId: "arn:aws:kms:us-east-1:146662336680:key/f12d12f2-9763-4d4b-894c-812be3e4cd2f"
      SecretString: "{\"username\":\"Ic4eTpiListener\",\"password\":\"Ic4eTpiListener-password\"}"
Parameters: {}
Metadata: {}
Conditions: {}